edition = "2021"
max_width = 100
use_small_heuristics = "Max"
reorder_imports = true
newline_style = "Unix"

# The `imports_granularity` and `group_imports` options we'd like to use
# are nightly-only as of 2026-04. Re-enable them once they stabilise.
